import { ITransactionRepository } from "../../../Domain/Repositories/ITransactionRepository";
import { IPaymentGateway } from "../../../Domain/Interfaces/IPaymentGateway";
import { CreateOrderDTO } from "../../DTOs/CreateOrderDTO";
import { CREDIT_PACKAGES } from "../../../Domain/ValueObjects/CreditPackage";
import { Transaction } from "../../../Domain/Entities/Transaction";

export class CreateCreditOrder {
  constructor(
    private transactionRepo: ITransactionRepository,
    private paymentGateway: IPaymentGateway,
  ) {}

  async execute(dto: CreateOrderDTO): Promise<{
    orderId: string;
    amount: number;
    currency: string;
    keyId: string;
  }> {
    const pkg = CREDIT_PACKAGES.find((p) => p.id === dto.packageId);
    if (!pkg) {
      throw new Error("Invalid package selected");
    }

    // Amount in smallest currency unit (paise)
    const amountInPaise = pkg.price * 100;
    const currency = "INR";

    // 1. Create order in Razorpay
    const receiptId = `rcpt_${dto.userId.substring(0, 10)}_${Date.now()}`;
    const orderId = await this.paymentGateway.createOrder(
      amountInPaise,
      currency,
      receiptId,
    );

    // 2. Create pending transaction in DB
    // Constructor Config:
    // id, userId, type, amount, paymentAmount, razorpayOrderId, razorpayPaymentId, status, metadata, createdAt
    const transaction = new Transaction(
      "", // ID (generated by DB)
      dto.userId,
      "CREDIT_PURCHASE", // Type
      pkg.credits,
      pkg.price, // paymentAmount
      orderId, // razorpayOrderId
      null, // razorpayPaymentId
      "PENDING", // status
      { packageId: pkg.id, packageName: pkg.name },
      new Date(),
    );

    await this.transactionRepo.create(transaction);

    // 3. Return details to frontend
    return {
      orderId,
      amount: amountInPaise,
      currency,
      keyId: process.env.RAZORPAY_KEY_ID || "",
    };
  }
}
